version: "3.9"
services:
  cve-web:
    build: cve-web
    hostname: websvr
    domainname: websvr.test
    environment:
      - POC_USERNAME=user
      - POC_PASSWORD=1qaz2wsx
    networks:
      cve-net:
        ipv4_address: 172.16.238.10
    ports:
      - "8080:8080"
  cve-poc:
    build: cve-poc
    hostname: ldapsvr
    domainname: ldapsvr.test
    environment:
      - POC_ADDR=172.16.238.11
      - POC_PORT=80
      - LISTENER_ADDR=10.10.10.31
      - LISTENER_PORT=9001
    networks:
      cve-net:
        ipv4_address: 172.16.238.11
networks:
  cve-net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1

# ldap
# rmi
# dns
# nis
# nds
# corba

